### ISSUE TITLE
MakeMKV found 0 Titles

### ISSUE THREAD

**Issue by nickrupert7** [JasonMillward/Autorippr#114]
Now that everything is working, I was trying to rip an actual DVD. I ran `python autorippr.py --all`, and the DVD actually ripped to my output folder. The disk ejected, but then I got an error saying something along the lines of "file no longer exists" (sorry I can't be more specific - I forgot to save it, and I'm unable to replicate it, as I'm about to explain).
Now, the movie won't even rip any more. I removed all of the contents of the previous rip from the output folder, and I run the command with `--debug` which gives the following output:
```
Rip - DEBUG - Ripping Initialized
Rip - DEBUG - Checking for DVDs
Rip - DEBUG - 1 DVDs found
Makemkv - DEBUG - MakeMKV found 0 titles
Rip - INFO - No movie titles found
Rip - INFO - Try decreasing 'minLength' in the config and try again
Compress - DEBUG - Compressing initialized
Compress - DEBUG - Looking for movies to compress
Compress - INFO - Queue does not exist or is empty
Extras - INFO - No movies ready for filebot
```
However, my minlength in settings.cfg is 0. This may be a problem with MakeMKV, but it's odd to me that it worked (kind of) once, then ceased to work. 

So really this is two questions - how can I get it to rip again, and what am I doing wrong to cause the movie not to compress when it DOES rip?

EDIT:
I did notice that there was another issue similar to this, but it seemed like the solution just had to do with updating the software, but I have the newest version.

EDIT:
I ran the script with a different DVD and I was able to replicate my previous error
```
...
Compress - DEBUG - Compressing Initialized
Compress - DEBUG - Looking for movies to compress
Compression - DEBUG - /home/nick/Documents/Output/Little Mermaid Usa/title08.mkv
Compression - ERROR - Input file no longer exists
...
```

EDIT:
I have now experienced the error with two separate movies. They're seen by MakeMKV the first time, then they fail to compress because the input file no longer exists, then MakeMKV can't find a main title when I try to re-rip even though the minLength is 0

**Comment by JasonMillward** [comment]
`Compression - Input file no longer exists` is interesting, it could be that makemkv is saving the wrong file name in the sqlite database. 

But I'm a little more perplexed with MakeMKV sporadically having issues with finding titles. I'll have to look into that a bit more. 


If possible, could you post the output from `/tmp/makemkvMessages` from an erroring disc?

**Comment by nickrupert7** [comment]
Hi Jason! Sorry for the delayed response, I've been on vacation.
I can post that file as soon as I get home, but I also thought I should mention that I just finished building the machine that the software will ACTUALLY be running on, and I can test it on there first just to make sure that the error isn't something to do with the fact that it's running on a virtual machine on my Mac.
Thanks, and look for my error file in the next few days!

**Comment by nickrupert7** [comment]
Here's the file! Still haven't had a chance to test it on my server, but I will in the next few days. [makemkvMessages.txt](https://github.com/JasonMillward/Autorippr/files/332661/makemkvMessages.txt)

**Comment by JasonMillward** [comment]
There are a lot of errors that MakeMKV is spitting out
```
Cells 3-end were skipped due to cell commands (structure protection?)
```
```
Error 'Scsi error - MEDIUM ERROR:UNRECOVERED READ ERROR' occurred while reading '/VIDEO_TS/VTS_01_1.VOB' at offset '2048'
```

I think the disk you have selected is just protected too well for MakeMKV to decrypt on it's own. 

It could be a Disney DRM issue or it could be a mounting issue. 
Try once more when you mount the disk, it would be a good idea to eliminate one possibility.

**Comment by nickrupert7** [comment]
Yesterday I was able to test a movie on the actual server, and it worked! I chose to rip and compress a non-Disney movie (Les Miserables), and in addition, I mounted it. Not only did it rip seamlessly, it compressed without the issue I mentioned before where the file no longer exists. So ultimately, it seems like one of those three changes fixed the problems I was having.

For future users that may run into similar issues, please note that I did find a solution to ripping movies with stronger than usual protection: Rip using the MakeMKV _desktop_ program. For some reason, the command line version seems to struggle at times, whereas the desktop program seems to work without a problem. The only disadvantage to this is you lose the automation of Autorippr, but here's the best solution I could find:
1. If you're using Ubuntu Server, you can actually update the OS to include a GUI with `sudo apt-get install ubuntu-desktop`. If you're already using Ubuntu Desktop, you can skip this step.
2. If you're using Ubuntu Server with the intent to be headless, set up Remote Desktop (see the link below) so you can use the desktop environment from another computer.
3. Install the MakeMKV desktop program
4. Manually rip your movie
5. If you want, run Autorippr compression (is there a run command to run the FileBot part of the script without `--all`?)

Note- I'm going to leave this thread open for a few more days, just in case I hit one of those issues again as I finalize my system.

**Comment by nickrupert7** [comment]
Ugg, I'm getting a new error. Details:
I'm running on my server, instead of VirtualBox on my Mac
In this instance, I chose to rip The Theory of Everything, Blu Ray

autorippr.log reads:
```
Rip - INFO - It took 22 minute(s) to complete the ripping of The_Theory_of_Everything_t00.mkv from Theoryofeverything Na
Compress - INFO - Compressing The_Theory_of_Everything_t00.mkv from Theoryofeverything Na
HandBrake - ERROR - HandBrakeCLI (compress) returned status code: 1
Compress - INFO - Compression did not compete successfully
Compress - INFO - Queue does not exist or is empty
Extras - INFO - No videos ready for filebot
```

And here is my [settings.cfg](https://github.com/JasonMillward/Autorippr/files/340532/settings.cfg.txt)

**Comment by JasonMillward** [comment]
Can you run with `--debug` please?

**Comment by nickrupert7** [comment]
Seeing the debug file, I figured it out myself... I probably should have checked before I posted
I'll post the file so you can see, but it was just an invalid option I added to the HandBrake options
[autorippr.log.txt](https://github.com/JasonMillward/Autorippr/files/340563/autorippr.log.txt)

**Comment by nickrupert7** [comment]
Sorry to keep bothering...
New issue
[autorippr.log.txt](https://github.com/JasonMillward/Autorippr/files/340608/autorippr.log.txt)

**Comment by JasonMillward** [comment]
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=739784

>as a workaround one can define another audio encoder, for example -E ffaac instead of default faac:

```  
HandBrakeCLI --preset "High Profile" -E ffaac -i 00033.MTS -o converted/00033_h.mkv
```


So you could try changing the command line args in `settings.cfg`  to something like

```
    com:
        -   --x264-preset="medium"
        -   --two-pass
        -   -q 20
        -   --markers
        -   --x264-tune="film"
        -   --encoder="x264"
        -   -s 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
        -   --preset="High Profile"
        -   -E ffaac 

```

**Comment by nickrupert7** [comment]
As expected, your solution works

But darned if another one didn't come up... I'm back to the ORIGINAL issue I told you about...
[autorippr.log.txt](https://github.com/JasonMillward/Autorippr/files/344373/autorippr.log.txt)

**Comment by JasonMillward** [comment]
No worries, we all start somewhere. 

Does `/home/nick/Videos/Output/Hobbit Part1/` contain the movie file `The_Hobbit_An_Unexpected_Journey_t00.mkv` ?

**Comment by nickrupert7** [comment]
Sorry, I've already deleted the folder to re-attempt the ripping/compression process. It's possible that somehow my custom script to move all output to another folder is being called _before_ the completion of autorippr, even though I put it in the crontab to run after... I'll play around with it and see what happens, and if I get the error again I'll be sure _not_ to run my move script and let you know the results

**Comment by nickrupert7** [comment]
It looks like something odd was happening where my script to run autorippr then move the output was not running synchronously, so that problem has been solved.

I swear though, this thing just doesn't want me to succeed. There's a new error which has to do with HandBrake. It's funny because the error doesn't seem to stop me from getting a compressed mp4 or m4v file, yet autorippr.log shows that compression failed. The annoying part about this is that then, filbert never gets a chance to run because the movie "fails" in compression and seems to get knocked off the queue.

Note that I did try researching this issue, but most results had to do with Don Melton's video transcoding scripts and dealt with a different issue

[autorippr.log.txt](https://github.com/JasonMillward/Autorippr/files/349842/autorippr.log.txt)

**Comment by JasonMillward** [comment]
Occasionally handbrake outputs an error message that doesn't stop the encoding. This is one of those times. 

I added in a [quick check](https://github.com/JasonMillward/Autorippr/commit/d0bd124d9dc214d94a0a415443f2bab14d265977) to stop this from breaking Autorippr but have no way of testing this myself. Can I ask you to test this change? 

You'll just have to pull down the latest changes via `git pull` and try the same video again.

**Comment by nickrupert7** [comment]
I'd be happy to test it! Does this patch cover this error specifically, or all errors that don't stop Handbrake? I ask because I think I might be experiencing yet ANOTHER error, where Handbrake "fails to add angle #2", but it might be another case of error that doesn't break the compression. Or, it might be another curse from the Handbrake gods. Who knows
I'll try the patch and report back

**Comment by JasonMillward** [comment]
The patch covers the `udfread` error specifically. 

From my tests handbrake doesn't exit with a status code when it errors, so reading the output is required in order to know what happened.

**Comment by nickrupert7** [comment]
Alright, I'll try it out and let you know when I get home from work. I double checked though, and it's actually MakeMKV that gives that warning, not Handbrake

**Comment by nickrupert7** [comment]
Awesome! Your patch works, and it compressed The Hobbit flawlessly. I'll have to get back to you on the other failure I was talking about, and the inevitable new error I'm experiencing where FileBot fails (although it might be that FileBot legitimately doesn't find the movie)

**Comment by JasonMillward** [comment]
I fixed the "failed to add angle" error that should be a warning.
The filebot failing is a fault with the lookup system, I can change the title that gets sent to filebot and that might clear some of it up.

**Comment by nickrupert7** [comment]
Awesome! I've been playing around with FileBot as well to see what kind of naming would help it work. I noticed that Blu Rays tend to come with different names than their DVD companions, and it seems like DVD titles are a little closer to the query that FileBot would retrieve successfully. To clarify, I'm not talking about autorippr renaming, I'm talking about the title of the actual file that comes on the disk. I may just need to manually do the renaming and subtitles and stuff, which isn't a problem because I just got the server working perfectly with FTP, Remote Desktop, and SSH on private and public networks, so I have every means of connection I could ever need to easily do something like that manually.

**Comment by nickrupert7** [comment]
Update: I checked, and "Hobbit Part1" does not get anything in Opensubtitles, but The Hobbit: An Unexpected Journey, does. It seems that some things I will just need to rename manually. I'll see if FileBot works successfully on a DVD where the on-board name is closer to what it should be

**Comment by nickrupert7** [comment]
I'm also sorry to report that Star Wars still gets stopped by the "failed to add angle" problem, but the completed .mkv file still comes out (and i checked, it's not corrupted or incomplete in any way). I would post the log file, but it's the same as before. (I did also make sure to git pull)

**Comment by JasonMillward** [comment]
It's because I added the modification to the wrong line, sorry about that. Hopefully it works now 🙏.

**Comment by nickrupert7** [comment]
Yay!!!!!! It finally works!!!!
There is a new error with Filebot, but that's ok with me because I've learned that I'd actually rather manually rename the movies and add subtitles than have Filebot do it, because Filebot doesn't always do it how I'd like. Still, I thought I'd let you know in case you had the desire to investigate and fix it. If you need me to test any fixes for you, I'll be happy to, considering all you've done to help me, but I don't actually NEED the fix to move forward with my project.

Here's what the output shows:
```
Filebot - DEBUG - [MOVE] Rename [/home/nick/Videos/Output/A New Hope/A New Hope.mp4] to [/home/nick/Videos/Output/Star Wars (1977).mp4]
Filebot - DEBUG - Processed 1 files
Filebot - DEBUG - 
Extras - DEBUG - Rename failed
```

If you need anything else, let me know, and again, thank you SO much for all of your support. I wouldn't be where I am without you 😊
